export const skillDescriptions: Record<string, string> = {
  authority: "Intimidate the public. Assert yourself.",
  composure: "Straighten your back. Keep your poker face.",
  conceptualization: "Understand creativity. See Art in the world.",
  drama: "Play the actor. Lie and detect lies.",
  electrochemistry: "Go to party planet. Love and be loved by drugs.",
  empathy: "Understand others. Work your mirror neurons.",
  encyclopedia: "Call upon all your knowledge. Produce fascinating trivia.",
  endurance: "Take the blows. Don’t let the world kill you.",
  espritDeCorps: "Connect to Station 41. Understand cop culture.",
  halfLight: "Let the body take control. Threaten people.",
  handEyeCoordination: "Ready? Aim and fire.",
  inlandEmpire: "Hunches and gut feelings. Dreams in waking life.",
  interfacing: "Master machines. Pick locks and pockets.",
  logic: "Wield raw intellectual power. Deduce the world.",
  painThreshold: "Shrug off the pain. They’ll have to hurt you more.",
  perception: "See, hear and smell everything. Let no detail go unnoticed.",
  physicalInstrument: "Flex powerful muscles. Enjoy healthy organs.",
  reactionSpeed: "The quickest to react. An untouchable man.",
  rhetoric:
    "Practice the art of persuasion. Enjoy rigorous intellectual discourse.",
  savoirFaire: "Sneak under their noses. Stun with immense panache.",
  shivers: "Raise the hair on your neck. Tune in to the city.",
  suggestion: "Charm men and women. Play the puppet-master.",
  visualCalculus:
    "Reconstruct crime scenes. Make laws of physics work for the Law.",
  volition: "Hold yourself together. Keep your Morale up.",
};
